### ISSUE TITLE
error with telegram

### ISSUE THREAD

**Issue by benjaminfrombe** [danielskowronski/hetzner-auction-hunter#12]
seems there is an issue with the telegram class ...

Traceback (most recent call last):
  File "./hah.py", line 4, in <module>
    import httpx, json, telegram_send, argparse
  File "/usr/local/lib/python3.8/site-packages/telegram_send/__init__.py", line 2, in <module>
    from .telegram_send import configure, send
  File "/usr/local/lib/python3.8/site-packages/telegram_send/telegram_send.py", line 33, in <module>
    from telegram.constants import MAX_MESSAGE_LENGTH
ImportError: cannot import name 'MAX_MESSAGE_LENGTH' from 'telegram.constants' (/usr/local/lib/python3.8/site-packages/telegram/constants.py)

**Comment by danielskowronski** [comment]
Related to https://github.com/rahiel/telegram-send/issues/115, I'll configure proper pyenv and requirements.txt instead of relying on "latest"

**Comment by danielskowronski** [comment]
Fixed :)
